[project]
name = "funshell"
version = "1.0.13"
description = "A lightweight Python utility for executing shell commands with real-time or captured output."
readme = "README.md"
license = "MIT"
requires-python = ">=3.6"
dependencies = []
keywords = [ "shell", "subprocess", "command", "execute",]
[[project.authors]]
name = "牛哥"
email = "niuliangtao@qq.com"

[[project.authors]]
name = "farfarfun"
email = "farfarfun@qq.com"

[[project.maintainers]]
name = "牛哥"
email = "niuliangtao@qq.com"

[[project.maintainers]]
name = "farfarfun"
email = "farfarfun@qq.com"

[project.urls]
Organization = "https://github.com/farfarfun"
Repository = "https://github.com/farfarfun/funshell"
Releases = "https://github.com/farfarfun/funshell/releases"

[tool.setuptools]
license-files = []

[tool.setuptools.packages.find]
where = [ "src",]
